services:
  - type: web
    name: tokenizer-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DB_USER
        value: KLAUS
      - key: DB_PASSWORD
        value: !monCarapach0
      - key: DB_DSN
        value: myadb_high.adb.eu-frankfurt-1.oraclecloud.com

